apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-23
  namespace: ns23
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: fast-23
